(time-example "rember with follower (hard first)"
  (run 1 (q)
    (absento 'letrec q)
    (absento 'closure q)
    (absento 3 q)
    (absento 4 q)
    (absento 5 q)
    (absento 6 q)
    (follower
      q
      (fresh/d ()
        (evalo/d `(letrec ([rember (lambda (e l) : ((number list) -> list)
                                     ,q)])
                    (rember 5 (cons 6 (cons 5 (cons 6 '())))))
                 '(6))
        (evalo/d `(letrec ([rember (lambda (e l) : ((number list) -> list)
                                     ,q)])
                    (rember 5 (cons 5 (cons 6 '()))))
                 '(6))
        (evalo/d `(letrec ([rember (lambda (e l) : ((number list) -> list)
                                     ,q)])
                    (rember 6 (cons 5 (cons 6 '()))))
                 '(5))
        (evalo/d `(letrec ([rember (lambda (e l) : ((number list) -> list)
                                     ,q)])
                    (rember 5 '()))
                 '())))
    (evalo `(letrec ([rember (lambda (e l) : ((number list) -> list)
                               ,q)])
              (rember 5 (cons 6 (cons 5 (cons 6 '())))))
           '(6))
    (evalo `(letrec ([rember (lambda (e l) : ((number list) -> list)
                               ,q)])
              (rember 5 (cons 5 (cons 6 '()))))
           '(6))
    (evalo `(letrec ([rember (lambda (e l) : ((number list) -> list)
                               ,q)])
              (rember 6 (cons 5 (cons 6 '()))))
           '(5))
    (evalo `(letrec ([rember (lambda (e l) : ((number list) -> list)
                               ,q)])
              (rember 5 '()))
           '())))

(time-example "rember no follower (hard first)"
  (run 1 (q)
    (absento 'letrec q)
    (absento 'closure q)
    (absento 3 q)
    (absento 4 q)
    (absento 5 q)
    (absento 6 q)
    (evalo `(letrec ([rember (lambda (e l) : ((number list) -> list)
                               ,q)])
              (rember 5 (cons 6 (cons 5 (cons 6 '())))))
           '(6))
    (evalo `(letrec ([rember (lambda (e l) : ((number list) -> list)
                               ,q)])
              (rember 5 (cons 5 (cons 6 '()))))
           '(6))
    (evalo `(letrec ([rember (lambda (e l) : ((number list) -> list)
                               ,q)])
              (rember 6 (cons 5 (cons 6 '()))))
           '(5))
    (evalo `(letrec ([rember (lambda (e l) : ((number list) -> list)
                               ,q)])
              (rember 5 '()))
           '())))
